package seeder

import (
	"github.com/arfanxn/welding/internal/infrastructure/id"
	mtMachineRepository "github.com/arfanxn/welding/internal/module/material_test_machine/domain/repository"
	mtMethodRepository "github.com/arfanxn/welding/internal/module/material_test_method/domain/repository"
	mtServiceRepository "github.com/arfanxn/welding/internal/module/material_test_service/domain/repository"
	"github.com/arfanxn/welding/internal/module/shared/domain/entity"
	"github.com/arfanxn/welding/pkg/typeutil"
	factoryGo "github.com/bluele/factory-go/factory"
	"github.com/brianvoe/gofakeit/v7"
	"go.uber.org/fx"
)

var _ Seeder = (*MaterialTestServiceSeeder)(nil)

type MaterialTestServiceSeeder struct {
	idService           id.IdService
	mtServiceFactory    *factoryGo.Factory
	mtServiceRepository mtServiceRepository.MaterialTestServiceRepository
	mtMethodRepository  mtMethodRepository.MaterialTestMethodRepository
	mtMachineRepository mtMachineRepository.MaterialTestMachineRepository
}

type NewMaterialTestServiceSeederParams struct {
	fx.In

	IdService                     id.IdService
	MaterialTestServiceFactory    *factoryGo.Factory `name:"material_test_service_factory"`
	MaterialTestServiceRepository mtServiceRepository.MaterialTestServiceRepository
	MaterialTestMethodRepository  mtMethodRepository.MaterialTestMethodRepository
	MaterialTestMachineRepository mtMachineRepository.MaterialTestMachineRepository
}

func NewMaterialTestServiceSeeder(
	params NewMaterialTestServiceSeederParams,
) Seeder {
	return &MaterialTestServiceSeeder{
		idService:           params.IdService,
		mtServiceFactory:    params.MaterialTestServiceFactory,
		mtServiceRepository: params.MaterialTestServiceRepository,
		mtMethodRepository:  params.MaterialTestMethodRepository,
		mtMachineRepository: params.MaterialTestMachineRepository,
	}
}

func (s *MaterialTestServiceSeeder) Seed() error {
	mtServiceFactory := s.mtServiceFactory

	/*
		mtServiceIds := []string{
			"01MTS0YPH5WB7KM2BRRW264JZD", // 1
			"01MTSNRVZ9P08JRM2YWHQ2405N", // 2
			"01MTSVYQWDZVX8BD6PD42D7QQ2", // 3
			"01MTST9JXDTBN3C53K6S3DX9H9", // 4
			"01MTS7K5GCPB93GGB6BF9H0K84", // 5
			"01MTS64K4B6F87DZ5ZWHMPR7H9", // 6
			"01MTSCCQZ0MEYGQGTXQB0GKFPN", // 7
			"01MTS437KJT3YFJ16R03BA4CX0", // 8
			"01MTSMRDD9PMHS083DJ20WQ1NC", // 9
			"01MTSCNSK1W7SVTY07E05GKNTD", // 10
			"01MTS5ZS0V6WBZ8QRAKPYQEP3S",
			"01MTSC5V3FRDGMFA6XPK5YFRR5",
			"01MTSFF62R7WRFS3ADMY19WFQS",
			"01MTS429YJB8H4G91MMCQE439C",
			"01MTSQVWFVEM0WE143KX576FGN",
			"01MTSF1X4WQ371CC5G53AXYQKB",
			"01MTSVN4DQ65CE587FC5S67MZB",
			"01MTS5DQDC54B9C8W2HW8NCKR3",
			"01MTSPAVV2H1W0D2NGBZCACF2D",
			"01MTSXZC86K27C7NK028E775M3",
			"01MTSYRWGFFTDBD1JQ2CF61D7M",
			"01MTSCMC2MCSFMRYMQ7N8KGZQ8",
			"01MTSK4G2F9SJXPPYWM5A112YG",
			"01MTS0X7AT2K5FVW6YSMM1MFV3",
			"01MTSG35WTQ85FNRV31X1H3BRP",
			"01MTSQB15ARX9B8BY5MCZ1N0AM",
			"01MTS6E9XYPDJYJ5S934TNTS56",
			"01MTSJ7QG4AT1T56GZTW8NNMVJ",
			"01MTS8MZYPM68JF3CNSF2ZG8KM",
			"01MTS9J8Q0AEW0DEGZZ35XBVXY",
			"01MTSG546V41JNEPY9DBBT7WCJ",
			"01MTS3Z1ETWXVNXJ91QXX9DF5P",
			"01MTSZ7B59VN3F3RHZC83E3WJ3",
			"01MTSHMR3R6XH2DG2XW7QEG2X5",
			"01MTS4D87Q82WJ8J43S6NQWQEY",
			"01MTSFZ3JX91GGGWW2NFRB0A8Q",
			"01MTS1XW7CXM2PVPN1N2Z2R6G1",
			"01MTSRG6GZWTZ4W71TW9J7E63B",
			"01MTS3R1HYK9B3D3Z6F8B9A9P4",
			"01MTSQ6Y0C8MW8PG2K2NZ0CBKN",
			"01MTS2Q5FX07TEM43DFYGNWH1Y",
			"01MTSK9D46H5P2N2FQM5RNW63Q",
			"01MTSSPQNJGXH4GN3S4QF8HV2C",
			"01MTS8VEXNQXM02CK78C6SXJFG",
			"01MTS0Q98XMK2X346CF21N4J3R",
			"01MTS9PTXNFJ3Y0ZGC0TKBNEZP",
			"01MTSH45X7WZ4MPKTT8V3KAP8C",
			"01MTSEW44KTFY4C8B7W8ZEXK9M",
			"01MTS172QX4N9B31KLP2FQEGMN",
		}
	*/

	var mtServices []*entity.MaterialTestService

	mtMethods, err := s.mtMethodRepository.All()
	if err != nil {
		return err
	}

	mtMachines, err := s.mtMachineRepository.All()
	if err != nil {
		return err
	}

	mtServices = append(mtServices,
		// 1
		mtServiceFactory.MustCreateWithOption(map[string]any{
			"Id":          "01MTS0YPH5WB7KM2BRRW264JZD",
			"MachineId":   typeutil.Ptr(mtMachines[gofakeit.IntRange(0, len(mtMachines)-1)].Id),
			"MethodId":    typeutil.Ptr(mtMethods[gofakeit.IntRange(0, len(mtMethods)-1)].Id),
			"ServiceCode": "UTM",
			// Unit, Price, CreatedAt, UpdatedAt are generated by factory
		}).(*entity.MaterialTestService),
		// 2
		mtServiceFactory.MustCreateWithOption(map[string]any{
			"Id":          "01MTSNRVZ9P08JRM2YWHQ2405N",
			"MachineId":   typeutil.Ptr(mtMachines[gofakeit.IntRange(0, len(mtMachines)-1)].Id),
			"MethodId":    typeutil.Ptr(mtMethods[gofakeit.IntRange(0, len(mtMethods)-1)].Id),
			"ServiceCode": "UTK",
		}).(*entity.MaterialTestService),
		// 3
		mtServiceFactory.MustCreateWithOption(map[string]any{
			"Id":          "01MTSVYQWDZVX8BD6PD42D7QQ2",
			"MachineId":   typeutil.Ptr(mtMachines[gofakeit.IntRange(0, len(mtMachines)-1)].Id),
			"MethodId":    typeutil.Ptr(mtMethods[gofakeit.IntRange(0, len(mtMethods)-1)].Id),
			"ServiceCode": "SPEC",
		}).(*entity.MaterialTestService),
		// 4
		mtServiceFactory.MustCreateWithOption(map[string]any{
			"Id":          "01MTST9JXDTBN3C53K6S3DX9H9",
			"MachineId":   typeutil.Ptr(mtMachines[gofakeit.IntRange(0, len(mtMachines)-1)].Id),
			"MethodId":    typeutil.Ptr(mtMethods[gofakeit.IntRange(0, len(mtMethods)-1)].Id),
			"ServiceCode": "CNC",
		}).(*entity.MaterialTestService),
		// 5
		mtServiceFactory.MustCreateWithOption(map[string]any{
			"Id":          "01MTS7K5GCPB93GGB6BF9H0K84",
			"MachineId":   typeutil.Ptr(mtMachines[gofakeit.IntRange(0, len(mtMachines)-1)].Id),
			"MethodId":    typeutil.Ptr(mtMethods[gofakeit.IntRange(0, len(mtMethods)-1)].Id),
			"ServiceCode": "HT",
		}).(*entity.MaterialTestService),
		// 6
		mtServiceFactory.MustCreateWithOption(map[string]any{
			"Id":          "01MTS64K4B6F87DZ5ZWHMPR7H9",
			"MachineId":   typeutil.Ptr(mtMachines[gofakeit.IntRange(0, len(mtMachines)-1)].Id),
			"MethodId":    typeutil.Ptr(mtMethods[gofakeit.IntRange(0, len(mtMethods)-1)].Id),
			"ServiceCode": "SST",
		}).(*entity.MaterialTestService),
		// 7
		mtServiceFactory.MustCreateWithOption(map[string]any{
			"Id":          "01MTSCCQZ0MEYGQGTXQB0GKFPN",
			"MachineId":   typeutil.Ptr(mtMachines[gofakeit.IntRange(0, len(mtMachines)-1)].Id),
			"MethodId":    typeutil.Ptr(mtMethods[gofakeit.IntRange(0, len(mtMethods)-1)].Id),
			"ServiceCode": "CAD",
		}).(*entity.MaterialTestService),
		// 8
		mtServiceFactory.MustCreateWithOption(map[string]any{
			"Id":          "01MTS437KJT3YFJ16R03BA4CX0",
			"MachineId":   typeutil.Ptr(mtMachines[gofakeit.IntRange(0, len(mtMachines)-1)].Id),
			"MethodId":    typeutil.Ptr(mtMethods[gofakeit.IntRange(0, len(mtMethods)-1)].Id),
			"ServiceCode": "EDM",
		}).(*entity.MaterialTestService),
		// 9
		mtServiceFactory.MustCreateWithOption(map[string]any{
			"Id":          "01MTSMRDD9PMHS083DJ20WQ1NC",
			"MachineId":   typeutil.Ptr(mtMachines[gofakeit.IntRange(0, len(mtMachines)-1)].Id),
			"MethodId":    typeutil.Ptr(mtMethods[gofakeit.IntRange(0, len(mtMethods)-1)].Id),
			"ServiceCode": "HRA",
		}).(*entity.MaterialTestService),
		// 10
		mtServiceFactory.MustCreateWithOption(map[string]any{
			"Id":          "01MTSCNSK1W7SVTY07E05GKNTD",
			"MachineId":   typeutil.Ptr(mtMachines[gofakeit.IntRange(0, len(mtMachines)-1)].Id),
			"MethodId":    typeutil.Ptr(mtMethods[gofakeit.IntRange(0, len(mtMethods)-1)].Id),
			"ServiceCode": "MS",
		}).(*entity.MaterialTestService),
	)

	err = s.mtServiceRepository.SaveMany(mtServices)
	if err != nil {
		return err
	}

	return nil
}
