CREATE TABLE permissions (
  id CHAR(26) PRIMARY KEY NOT NULL,
  name VARCHAR(50) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT uc_permissions_name UNIQUE (name)
);